added clear error messages for different failures sending remote logs
Granulate/granulate-utils pull request #239
Opened 2024-05-09 12:11 UTC by david-granulating

2024-05-09 22:30 UTC, Jongy commented
I'll review it next week.

2024-05-13 13:07 UTC, Jongy commented on glogger/sender.py
> +SENDER_UNAUTHORIZED_MESSAGE = "REMOTE_LOGGER: Authentication error while sending logs to server, check gprofiler token"
Authentication or authorization? These are different, use one 😅

2024-05-13 13:08 UTC, Jongy commented on glogger/sender.py
> +                    f"REMOTE_LOGGER: Received 500 from server, gprofiler token is probably invalid / missing. "
```suggestion
                    f"REMOTE_LOGGER: Received 500 from server, token is probably invalid / missing. "
```

2024-05-13 13:29 UTC, Jongy requested changes
2 small comments

2024-05-15 10:45 UTC, david-granulating commented
@Jongy fixed 2 small comments

2024-05-15 11:30 UTC, Jongy approved these changes

2024-05-15 12:42 UTC, merged