try_acquire_mutex(): FD_CLOEXEC on the mutex
Granulate/granulate-utils pull request #67
Opened 2022-08-30 17:30 UTC by Jongy

2022-08-30 20:43 UTC, d3dave requested changes
Please explain why you need this. Since Python 3.4, all created fd's have CLOEXEC by default (https://docs.python.org/3.6/library/os.html#inheritance-of-file-descriptors):

```
ubuntu@ubuntu18:~$ cat test.py
import os
from granulate_utils.linux import mutex

mutex.try_acquire_mutex('test')
s = mutex._mutexes['test']
print('fd', s.fileno())
os.execlp('ls', 'ls', '-l', '/proc/self/fd')
ubuntu@ubuntu18:~$ python3 test.py
fd 3
total 0
lrwx------ 1 ubuntu ubuntu 64 Aug 30 23:41 0 -> /dev/pts/0
lrwx------ 1 ubuntu ubuntu 64 Aug 30 23:41 1 -> /dev/pts/0
lrwx------ 1 ubuntu ubuntu 64 Aug 30 23:41 2 -> /dev/pts/0
lr-x------ 1 ubuntu ubuntu 64 Aug 30 23:41 3 -> /proc/10677/fd
lrwx------ 1 ubuntu ubuntu 64 Aug 30 23:41 6 -> /dev/pts/0
```

2022-08-30 20:45 UTC, d3dave commented
Also, here's proof that test works the other way around as well:

```
ubuntu@ubuntu18:~$ cat test.py
import os
from granulate_utils.linux import mutex

mutex.try_acquire_mutex('test')
s = mutex._mutexes['test']
print('fd', s.fileno())
os.set_inheritable(s.fileno(), True)
os.execlp('ls', 'ls', '-l', '/proc/self/fd')
ubuntu@ubuntu18:~$ python3 test.py
fd 3
total 0
lrwx------ 1 ubuntu ubuntu 64 Aug 30 23:44 0 -> /dev/pts/0
lrwx------ 1 ubuntu ubuntu 64 Aug 30 23:44 1 -> /dev/pts/0
lrwx------ 1 ubuntu ubuntu 64 Aug 30 23:44 2 -> /dev/pts/0
lrwx------ 1 ubuntu ubuntu 64 Aug 30 23:44 3 -> 'socket:[1775411]'
lr-x------ 1 ubuntu ubuntu 64 Aug 30 23:44 4 -> /proc/10719/fd
lrwx------ 1 ubuntu ubuntu 64 Aug 30 23:44 6 -> /dev/pts/0
```

2022-08-31 09:26 UTC, Jongy commented
Hmmph. I didn't know that. I made this change because I switched gProfiler to use `try_acquire_mutex`, and gProfiler's `grab_gprofiler_mutex` does the CLOEXEC thing while `try_acquire_mutex` did not.

I'll change it to a comment

2022-08-31 09:31 UTC, d3dave approved these changes

2022-08-31 09:32 UTC, merged