Cloud info: Add support for Oracle Cloud
Granulate/granulate-utils pull request #76
Opened 2022-09-21 10:10 UTC by uriariel

2022-09-27 08:26 UTC, YoniKF requested changes

2022-09-27 08:26 UTC, YoniKF commented on granulate_utils/metadata/cloud.py
> +        memory=instance["shapeConfig"]["memoryInGBs"],
Other cloud provider classes don't have this attribute (yet), let's see can get memory information on them as well.
Also, rename to include the memory units (`memory_mb` or `memory_gb`).

2022-09-27 08:26 UTC, YoniKF commented on granulate_utils/metadata/cloud.py
> +        name=instance["hostname"],
For GCP we access `name` and not `hostname`. Find out if it matters and make the behavior here consistent.

2022-09-27 08:26 UTC, YoniKF commented on granulate_utils/metadata/cloud.py
> +        image=instance["image"],
Other classes have an `image_id` field, why is this one `image`?

2022-11-29 15:17 UTC, michelhe commented
@YoniKF @uriariel Status here?

2022-12-04 08:47 UTC, YoniKF commented
PR is getting stale, closing.

2022-12-04 08:47 UTC, closed without merging